### ISSUE TITLE
Raw annotated dataset

### ISSUE THREAD

**Issue by itsmemala** [sougata-ub/personality-response-generation#1]
Hi, I'm a research student and would like to use the datasets you've created, particularly the intent and trait labels for topical-chat. I was wondering if you could upload a raw version of the annotated dataset?

**Comment by sougata-ub** [comment]
Hi @itsmemala ,
Unfortunately, due to a glitch at our end, we don't have the raw version of the annotated dataset. You can use the encoded version of the data by decoding using the appropriate tokenizers. 

The annotated encoded datasets are present here: 
Wizard of Wikipedia data for BART: https://drive.google.com/file/d/1wFjltDqb8HCY2zaXr2bEzU8_yYIaUyWQ/view?usp=sharing
Wizard of Wikipedia data for Blenderbot: https://drive.google.com/file/d/1CetIysBWgM6-DQs3GCnciAg-AX-z5OdB/view?usp=sharing
Topical Chat data for BART: https://drive.google.com/file/d/1OcL1_9dJEQoL6svsF8ANt0NaBykVm3O3/view?usp=sharing
Topical Chat data for Blenderbot: https://drive.google.com/file/d/1NzLyYM3i5fWQaDKGFnhNNsayJkSmDsrF/view?usp=sharing
